### ISSUE TITLE
Difficulty integrating Blazor component

### ISSUE THREAD

**Issue by pjhenning** [fsbolero/Bolero#170]
Hello, I am having trouble getting a Blazor component (https://github.com/serdarciplak/BlazorMonaco) to play nice with Bolero. The instructions for this component say to include the following:
```
@using BlazorMonaco
@using BlazorMonaco.Bridge
```
in the project `_imports.razor` file, but Bolero does not use this so instead I have:
```
open BlazorMonaco
open BlazorMonaco.Bridge
```
in my `Main.fs`. And am instantiating the component via: `let editor = comp<MonacoEditor> [] []`, and then including it in the final html output via a template with the hole `${Editor}`. When I run the app, the component does not appear, and the following error message is logged to the console:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'addEventListener' of null
      TypeError: Cannot read property 'addEventListener' of null
          at new e (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:228:287)
          at Object.b [as addDisposableListener] (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:228:538)
          at new t (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2223:518)
          at http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2239:638
          at g (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2239:213)
          at new t (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2239:584)
          at k (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2240:689)
          at Object.T [as create] (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2241:54)
          at Object.create (http://localhost:5000/_content/BlazorMonaco/jsInterop.js:39:36)
          at http://localhost:5000/_framework/blazor.webassembly.js:1:9873
Microsoft.JSInterop.JSException: Cannot read property 'addEventListener' of null
TypeError: Cannot read property 'addEventListener' of null
    at new e (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:228:287)
    at Object.b [as addDisposableListener] (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:228:538)
    at new t (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2223:518)
    at http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2239:638
    at g (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2239:213)
    at new t (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2239:584)
    at k (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2240:689)
    at Object.T [as create] (http://localhost:5000/_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js:2241:54)
    at Object.create (http://localhost:5000/_content/BlazorMonaco/jsInterop.js:39:36)
    at http://localhost:5000/_framework/blazor.webassembly.js:1:9873
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x3b23458 + 0x00034> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x3ad9ca8 + 0x000e4> in <filename unknown>:0 
  at BlazorMonaco.MonacoEditorBase.Create (System.String id, BlazorMonaco.Bridge.StandaloneEditorConstructionOptions options) <0x3a0c698 + 0x0016c> in <filename unknown>:0 
  at BlazorMonaco.MonacoEditor.OnAfterRenderAsync (System.Boolean firstRender) <0x3a0a6e8 + 0x0014a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x3ae9cd0 + 0x000b6> in <filename unknown>:0 
f.printErr @ blazor.webassembly.js:1
```
Can anyone suggest a way forward for this? I think that something from `BlazorMonaco.Bridge` needs to get passed along to/included with the `MonacoEditor` component, but I am not sure how to do this.

**Comment by pjhenning** [comment]
Apparently the component requires an "Id" attribute, however this is not indicated at all by the error message. Ideally this is something that would be more clearly reported, but is likely beyond the capacity of the F# type system to be responsible for, so i don't blame Bolero for the confusion.
