### ISSUE TITLE
NullPointerException during initial Router.inferWithModel on .NET 5.0

### ISSUE THREAD

**Issue by kojo12228** [fsbolero/Bolero#191]
I have a [small test project](https://github.com/kojo12228/PmaBolero) that I tried to run after upgrading to .NET 5.0 via Visual Studio. The following exception was thrown:

```
An exception of type 'System.TypeInitializationException' occurred in PmaBolero.Client.dll but was not handled in user code: 'The type initializer for '<StartupCode$PmaBolero-Client>.$PmaBolero.Client.Pages.Main' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.NullReferenceException : Object reference not set to an instance of an object.
   at Bolero.RouterImpl.getCtor(FSharpFunc`2 defaultPageModel, UnionCaseInfo case)
   at Bolero.RouterImpl.parseEndPointCase(FSharpFunc`2 getSegment, FSharpFunc`2 defaultPageModel, UnionCaseInfo case)
   at Bolero.RouterImpl.unionSegment(FSharpFunc`2 getSegment, FSharpFunc`2 defaultPageModel, Type ty)
   at Bolero.RouterImpl.getSegment(Dictionary`2 cache, FSharpFunc`2 defaultPageModel, Type ty)
   at Bolero.Router.inferWithModel[ep,model,msg](FSharpFunc`2 makeMessage, FSharpFunc`2 getEndPoint, FSharpFunc`2 defaultPageModel)
   at <StartupCode$PmaBolero-Client>.$PmaBolero.Client.Pages.Main..cctor()
```

- I re-installed .NET Core 3.1 and confirmed that the code runs fine.
- Upgrading Bolero from 14 to 15 and updating Blazor packages didn't resolve the issue.
- On my computer a Hello World Bolero 14 application ran with no issue.

The related defaultModel and router within [Main.fs](https://github.com/kojo12228/PmaBolero/blob/master/src/PmaBolero.Client/Pages/Main.fs):

```fsharp
let defaultModel = function
    | Home -> ()

    | SignIn model -> Router.definePageModel model SignIn.initModel
    | SignUp model -> Router.definePageModel model SignUp.initModel

    | ViewProjects model -> Router.definePageModel model ViewGroup.Project.initModel
    | ViewProject (_, model) -> Router.definePageModel model ViewItem.Project.initModel
    | CreateProject model -> Router.definePageModel model Create.Project.initModel
    | EditProject (_, model) -> Router.definePageModel model Edit.Project.initModel

    | ViewEmployees model -> Router.definePageModel model ViewGroup.Employee.initModel
    | ViewEmployee (_, model) -> Router.definePageModel model ViewItem.Employee.initModel
    | CreateEmployee model -> Router.definePageModel model Create.Employee.initModel
    | EditEmployee (_, model) -> Router.definePageModel model Edit.Employee.initModel

    | ViewDepartments model -> Router.definePageModel model ViewGroup.Department.initModel
    | ViewDepartment (_, model) -> Router.definePageModel model ViewItem.Department.initModel

//...

let router = Router.inferWithModel SetPage (fun model -> model.Page) defaultModel
```

The only idea I have is that it's related to `Home` not calling Router.definePageModel and instead returning unit. Any help is much appreciated.

**Comment by Tarmil** [comment]
Yes, I have a Bolero version 0.16 for .NET 5 that will be released very soon and fixes this issue. I'll update this issue when it's out!

**Comment by Tarmil** [comment]
Bolero 0.16 is now released, and with it, this issue is fixed.
