### ISSUE TITLE
Hello world fails 

### ISSUE THREAD

**Issue by Walms** [fsbolero/Bolero#220]
Following the getting started tutorial ends with an exception on the first page load of Hello World. 

```
dotnet new -i Bolero.Templates
dotnet new bolero-app -o HelloWorld
cd HelloWorld

C:\Users\daniel\Dev\cabmateQuickView\HelloWorld>dotnet run -p src/HelloWorld.Server
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\daniel.walmsley\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Content root path: C:\Users\daniel.walmsley\Dev\cabmateQuickView\HelloWorld\src\HelloWorld.Server
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Fallback {*path:nonfile}'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Fallback {*path:nonfile}'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM8GVSFD60BO", Request id "0HM8GVSFD60BO:00000002": An unhandled exception was thrown by the application.
      System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at <StartupCode$Bolero-Server>.$Extensions.RenderPage@53.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - - - 500 0 - 92.3921ms
```

The following are the .NET SDK versions

```
C:\Users\daniel\Dev\cabmateQuickView\HelloWorld>dotnet --list-sdks
3.1.300 [C:\Program Files\dotnet\sdk]
5.0.102 [C:\Program Files\dotnet\sdk]
5.0.201 [C:\Program Files\dotnet\sdk]
```

**Comment by Tarmil** [comment]
Yes sorry, mistakes were made in the latest release. Fixing this immediately.

**Comment by Tarmil** [comment]
This is now fixed with Bolero.Templates 0.17.10 and Bolero.HotReload 0.17.9.
