### ISSUE TITLE
Exception when building from Visual Studio

### ISSUE THREAD

**Issue by Tarmil** [fsbolero/Bolero#25]
With added logging in Bolero.Build/Task, this is the stack trace:

```
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error : FAILING HERE on C:\my\bolero\tests\Client\obj\Debug\netstandard2.0\blazor\linker\Bolero.dll: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.TypeReference.Resolve()
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.AddTypes()
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.BuildTypes()
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.BuildModule()
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.MetadataBuilder.BuildMetadata()
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Mono.Cecil.AssemblyDefinition.Write(String fileName)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Bolero.Build.BoleroTask.StripFile(String f)
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error :    at Bolero.Build.BoleroTask.Execute()
3>C:\my\bolero\src\Bolero.Build\Bolero.Build.targets(13,5): error : Failed to resolve assembly: 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
```

It seems Cecil looks up dependencies incorrectly when writing the modified assembly. Not sure why it does it differently when building from VS or from command line.

**Comment by Tarmil** [comment]
Closing as stale.
