### ISSUE TITLE
How to define AntDesign Table in Boleror

### ISSUE THREAD

**Issue by fwaris** [fsbolero/Bolero#276]
I am trying to use AntDesign table. The Razor syntax for the table is: 

```Razor
<Table @ref="table"
       TItem="WeatherForecast"
       DataSource="@forecasts"
       Total="_total"
       @bind-PageIndex="_pageIndex"
       @bind-PageSize="_pageSize"
       @bind-SelectedRows="selectedRows"
       OnChange="OnChange">
  <Selection Key="@(context.Id.ToString())" />
  <PropertyColumn Property="c=>c.Id" Sortable />
  <PropertyColumn Property="c=>c.Date" Format="yyyy-MM-dd" Sortable />
  <PropertyColumn Property="c=>c.TemperatureC" Sortable />
  <PropertyColumn Title="Temp. (F)" Property="c=>c.TemperatureF" />
  <PropertyColumn Title="Hot" Property="c=>c.Hot">
    <Switch @bind-Value="@context.Hot"></Switch>
  </PropertyColumn>
  <PropertyColumn Property="c=>c.Summary" Sortable />
  <ActionColumn>
    <Space>
      <SpaceItem><Button Danger OnClick="()=>Delete(context.Id)">Delete</Button></SpaceItem>
    </Space>
  </ActionColumn>
</Table>
```

I tried the following but there is a runtime time error "Unable to set property 'ChildContent'" due to some casting issue (see below):
```F#
let alarmGrid (alarms:Ak[]) : Node  =
    comp<Table<Ak>> { 
        "DataSource" => ResizeArray(alarms)     
        comp<PropertyColumn<Ak,int>> {
            "Title" => "Id"
            "Property" => (fun (o:Ak) -> o.Id)   
        }        
    }
```
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to set property 'ChildContent' on object of type 'AntDesign.Table`1[[AlrmRcUI.Client.Model+AlarmStats`1[[System.Tuple`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], AlrmRcUI.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Specified cast is not valid.
System.InvalidOperationException: Unable to set property 'ChildContent' on object of type 'AntDesign.Table`1[[AlrmRcUI.Client.Model+AlarmStats`1[[System.Tuple`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], AlrmRcUI.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[Table`1,RenderFragment`1](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

I am new to Bolero. Have read the documentation and examples but I don't know solve this specific issue.

**Comment by fwaris** [comment]
The following seems to work 
```F#
let alarmGrid (alarms:Ak[]) : Node  =
    comp<Table<Ak>> { 
        "DataSource" => ResizeArray(alarms) 
        "PageSize" => 100
        attr.fragmentWith "ChildContent" <| fun (context: Ak) ->
            concat {
                comp<PropertyColumn<Ak,int>> {
                    "Title" => "Id"
                    "Property" => (fun (o:Ak) -> o.Id)}
                comp<PropertyColumn<Ak,string>> {
                    "Title" => "Key"
                    "Property" => (fun (o:Ak) -> string o.Alarm_key)}
            }
    }

However, I don't see the actual rows - only the paging footer. Anyway will close for now.
```
