### ISSUE TITLE
Razor hosting template seems to be broken with 7.x asp.net bits

### ISSUE THREAD

**Issue by fwaris** [fsbolero/Bolero#325]
When I build and run an app created with *--hostpage=razor*, I get a "fallback endpoint not found" error:

```C#
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HMTI0LABRCFE", Request id "0HMTI0LABRCFE:00000001": An unhandled exception was thrown by the application.

System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
## Background
I am trying to integrate Microsoft AD authentication into my application. 

There is a [sample](https://github.com/anderslm/fsharp-bolero-azure-ad)  that I am trying to follow. It uses Razor hosting. I can get it to compile with the latest bits but it also suffers from the above issue, after getting it to compile.

Ultimately though, I would like to build upon the [documented AD authentication mechanism for wasm blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-authentication-library?view=aspnetcore-7.0&tabs=visual-studio). Its based on [the blazor wapper for msal.js](Microsoft.AspNetCore.Components.WebAssembly.Authentication) and that too is very razor specific.

**Comment by fwaris** [comment]
The Razor hosted template based project is working now.

There were two separate issues.

The first is that I was using VS 2022 preview. It seems the template does not work with the new version of asp.net. Switching to .net 7.0.400 via global.json fixed this issue.

The second is that the template needs a minor fix in the Razor page. The namespace for IBoleroHostConfig is not correct in the template. the code should be as follows:

```
...
@using Bolero.Server
@inject IBoleroHostConfig BoleroHostConfig
...
```

**Comment by fwaris** [comment]
Bolero sample that shows:
- Active Directory authentication (WASM msal.js)
- MS Graph API invocation
- WASM debugging configuration

https://github.com/fwaris/BoleroWasm
