### ISSUE TITLE
Debugging support

### ISSUE THREAD

**Issue by OnurGumus** [fsbolero/Bolero#37]
Is there any debugging support?

**Comment by Tarmil** [comment]
The easiest way to debug is by running the application using server-side Blazor. We should add a documentation page about this, and also maybe add a way to make it a bit easier; but in short, assuming you have a project including the server side:

1. Add the following to your server-side `ConfigureServices`:

    ```fsharp
        services
            .AddServerSideBlazor<Client.Startup>() // Replace with your client-side startup class
            // .OtherMethods()...
        |> ignore
    ```

2. In your server-side `Configure`, replace `UseBlazor` with `UseServerSideBlazor`.

3. In your www/index.html, replace `blazor.webassembly.js` with `blazor.server.js`

4. Run your server project with the debugger of your choice.

**Comment by OnurGumus** [comment]
Is it possible to do client-side debugging ?

**Comment by Tarmil** [comment]
There's some experimental debugging support for Blazor: https://docs.microsoft.com/fr-fr/aspnet/core/razor-components/debug?view=aspnetcore-3.0 but I've never actually tried it on Bolero.

**Comment by deyanp** [comment]
Tried Chrome debugging, but could not make it working, here are my steps (HelloWorld.Server does not work as there is no debugging proxy listening there):

1. dotnet run -p src/HelloWorld.Client -c Debug
2. close all chrome instances!
3. "%programfiles(x86)%\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 http://localhost:5000
4. Ctrl-Shft-I
5. Focus on the app, Shft-Alt-D

```
got exception System.AggregateException: One or more errors occurred. (Format of the executable (.exe) or library (.dll) is invalid.) ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadMetadata()
   at Mono.Cecil.PE.ImageReader.ReadPortablePdb(Disposable`1 stream, String file_name)
   at Mono.Cecil.Cil.PortablePdbReaderProvider.GetSymbolReader(ModuleDefinition module, Stream symbolStream)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at WsProxy.AssemblyInfo..ctor(Byte[] assembly, Byte[] pdb)
   at WsProxy.DebugStore..ctor(String[] loaded_files)
   at WsProxy.MonoProxy.RuntimeReady(CancellationToken token)
   at WsProxy.MonoProxy.OnDefaultContext(Int32 ctx_id, JObject aux_data, CancellationToken token)
   at WsProxy.MonoProxy.AcceptEvent(String method, JObject args, CancellationToken token)
   at WsProxy.WsProxy.OnEvent(String method, JObject args, CancellationToken token)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at WsProxy.WsProxy.Run(Uri browserUri, WebSocket ideSocket)
---> (Inner Exception #0) System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadMetadata()
   at Mono.Cecil.PE.ImageReader.ReadPortablePdb(Disposable`1 stream, String file_name)
   at Mono.Cecil.Cil.PortablePdbReaderProvider.GetSymbolReader(ModuleDefinition module, Stream symbolStream)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at WsProxy.AssemblyInfo..ctor(Byte[] assembly, Byte[] pdb)
   at WsProxy.DebugStore..ctor(String[] loaded_files)
   at WsProxy.MonoProxy.RuntimeReady(CancellationToken token)
   at WsProxy.MonoProxy.OnDefaultContext(Int32 ctx_id, JObject aux_data, CancellationToken token)
   at WsProxy.MonoProxy.AcceptEvent(String method, JObject args, CancellationToken token)
   at WsProxy.WsProxy.OnEvent(String method, JObject args, CancellationToken token)<---

```
