### ISSUE TITLE
“System.MissingMethodException: Cannot create an abstract class” when passing function as an argument in Remote service.

### ISSUE THREAD

**Issue by pizycki** [fsbolero/Bolero#45]
Hello everyone,

Thank you for this library, I’m having really good time using it :)

I was creating a simple data grid when I got on this error. It occurs when I’m trying to pass a predicate to the server-side as an argument.

```F#
type RuleService =
    {
        /// Gets rules by predicate
        getRules: (Rule -> bool) -> Async<Rule[]>
    }


type RuleService(env: IHostingEnvironment) =
    inherit RemoteHandler<Client.Main.RuleService>()

    override this.Handler =
        {
            getRules = Remote.withContext <| fun http _ -> async {
                return rules
            }
        }
```

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLM7NQBFM0I3", Request id "0HLM7NQBFM0I3:00000003": An unhandled exception was thrown by the application.
System.MissingMethodException: Cannot create an abstract class.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at Bolero.Json.objectDecoder@1287-6.Invoke(Value x)
   at <StartupCode$Bolero-Server>.$Remoting.run@116(FSharpFunc`2 decoder, FSharpFunc`2 encoder, Object meth, MethodInfo callMeth, MethodInfo output, HttpContext ctx, Unit unitVar0)
   at <StartupCode$Bolero-Server>.$Remoting.clo@115.Invoke(IAuthorizationService auth, HttpContext ctx)
   at Bolero.Remoting.Server.RemotingService.TryHandle(HttpContext ctx, IAuthorizationService auth)
   at Microsoft.FSharp.Collections.ArrayModule.TryPick[T,TResult](FSharpFunc`2 chooser, T[] array)
   at <StartupCode$Bolero-Server>.$Remoting.UseRemoting@233.Invoke(HttpContext ctx, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

The error is thrown at runtime.

I haven’t checked exactly what’s happening under the hood, but it clearly has something to do with predicate serialization. 

I’m guessing Bolero (or Blazor) is using Newtonsoft as default JSON serializer which doesn’t support function serialization very well.

I’ve done very little research and found that [FsPickler can serialize functions](https://stackoverflow.com/a/51540437/864968).

Passing functions between client and server in frameworks like Bolero would be very beneficial, IMO.

Since I’m just a F# beginner and have very little practice in this land, I’d like to hear from you if I’m doing something wrong or there is a missing part in Bolero/Blazor which hasn’t been filled yet :)

**Comment by Tarmil** [comment]
Bolero uses its own serializer, not Newtonsoft, but you're right that it can't handle functions. That's something I've very rarely felt the need for; but it would be totally possible to add a format similar to FsPickler's.

**Comment by brikken** [comment]
@pizycki 
I believe it's a potential security risk to execute deserialized code. In a couple of scenarios, I believe there are better, and safer, ways to get around this.

In case the functions you want to pass are already defined at compile-time, I would simply put them in a shared library, used by both server and client, and serialize a reference to the desired function.

If the functions are created run-time (eg. using quotations or reflection), this generation is probably controlled by an underlying data logic. Instead, serialize and pass the data controlling the generation to the server, and again used a shared library that converts the data structure to the desired function.

In both situations, you own code either owns the function to be executed, or at least the code that generates the function to be executed, and not simply trusts that the serialized function that is received is not malicious.

**Comment by pizycki** [comment]
Totally agree, I didn't think about it back then.

Closing :)
