### ISSUE TITLE
Bolero 0.5 default template application won't do logon

### ISSUE THREAD

**Issue by BentTranberg** [fsbolero/Bolero#50]
I am using VS 2019 v 16.1.2. I have installed .NET Core 3.0 SDK v 3.0.100-preview5. I have installed the Bolero 0.5 template and created an application as described on the Getting started page.

The application seems to work just fine until I try to logon in the "Download data" page with a username and the password "password". There is no response when I click on the "Sign in" button.

This is from the output pane in VS 2019. I have included irrelevant repeating group of lines before and after the interesting part.

```
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/favicon.ico  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
BoleroSpike2.Client>       The file /index.html was not modified
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 6.125ms 304 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 5.397600000000001ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/favicon.ico  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
BoleroSpike2.Client>       The file /index.html was not modified
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 4.3846ms 304 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 6.0196000000000005ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 POST http://localhost:7982/books/signIn application/json; charset=utf-8 18
BoleroSpike2.Client> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
BoleroSpike2.Client>       An unhandled exception has occurred while executing the request.
BoleroSpike2.Client> System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
BoleroSpike2.Client> 
BoleroSpike2.Client>    at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
BoleroSpike2.Client>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client>    at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client>    at Microsoft.AspNetCore.Builder.AutoRebuildExtensions.<>c__DisplayClass4_0.<<UseDevServerAutoRebuild>b__1>d.MoveNext()
BoleroSpike2.Client> --- End of stack trace from previous location where exception was thrown ---
BoleroSpike2.Client>    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 5.4442ms 500 text/plain
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 5.0561ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
BoleroSpike2.Client>       Request starting HTTP/1.1 GET http://localhost:7982/bolero-reload  
BoleroSpike2.Client> info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
BoleroSpike2.Client>       Sending file. Request path: '/index.html'. Physical path: 'C:\devbox\BoleroSpike2\src\BoleroSpike2.Client\wwwroot\index.html'
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
BoleroSpike2.Client>       Request finished in 6.0516000000000005ms 200 text/html
BoleroSpike2.Client> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

```

**Comment by Tarmil** [comment]
I think the problem is that you are running the Client project. You need to set the Server project as the startup project to run the remoting server.

I'm not sure if there's a way to prevent other people from making the same mistake. Unfortunately there's no way to specify in the solution file which should be the startup project by default. And I don't think I can make the client project non-startable, because it needs to be an executable so that the wasm machinery can start it.

**Comment by granicz** [comment]
We should add a FAQ link to the website menu and point it to a page where we explain this and other typical gotchas.

**Comment by BentTranberg** [comment]
You can make the Server project the default startup project in the solution file, by simply making sure the Server project is listed first in the solution file. Visual Studio will honor this as long as there is no .vs or .suo or anything like that, which there normally isn't on first opening of the solution. I'm not familiar with VS Code.

I am not sure exactly which part(s) in the solution file determines the startup order, so I just fixed it in all three places - which looks tidier also. Seems to work well. I'm including a screenshot just to make it obvious what I did.

![diff](https://user-images.githubusercontent.com/15068882/59154869-62d1b880-8a7c-11e9-8ffa-3e0b7e32f2d2.jpg)

**Comment by BentTranberg** [comment]
BTW, there was also an error in yellow at the bottom of the web page that said "Unexpected response status: InternalServerError". That one contributed to putting me off track, because I thought it meant the server was at least running.

Another reason it didn't occur to me that Server should be the startup project, is that web programming in modern VS (post VS 2008) is quite new to me, and I guess I somehow got the impression there were mechanisms to handle dependencies and startup that I wasn't familiar with.

**Comment by Tarmil** [comment]
> You can make the Server project the default startup project in the solution file, by simply making sure the Server project is listed first in the solution file.

Oh that's nice, I didn't know that. I'll make that change in the template.

> BTW, there was also an error in yellow at the bottom of the web page that said "Unexpected response status: InternalServerError".

That was likely returned by the Blazor Dev server, which is the dummy server that gets started when you run a Blazor app directly from VS; although I don't know why it doesn't just return a 404.

**Comment by BentTranberg** [comment]
Thanks a lot! Everything will be all right then. I'm busy exploring Bolero, and is hugely impressed. I want to switch my business project from WebSharper to Bolero.

I don't know if you have a policy when it comes to changing titles on issues in order to reflect the actual cause when it is revealed, so I leave that decision to you. I'm thinking the title should now be something like "The Server project is not the default startup project in the solution file". (edit: But I guess it should also be in the template repo.)
